<h2>
	<a href="<?= $this->url(array('controller' =>'admin','action' => 'index')); ?>">Katalog</a>
<?php
	// doawanie specyfikacji
	switch ($this->controller) {
		case 'catalog':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Katalog</a><?php
			break;
		case 'district':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Obszar</a><?php
			break;
		case 'type':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Typ</a><?php
			break;
		case 'service':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Usł.</a><?php
			break;
		case 'service_cost':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>"><abbr title="Koszty usług dla każdego wpisu">K.U.W.</abbr></a><?php
			break;
		case 'image':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Graf.</a><?php
			break;
		case 'promotype':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">P.Typ</a><?php
			break;
		case 'promotime':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">P.Czas</a><?php
			break;
		case 'options':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Opcje</a><?php
			break;
		case 'optionshas':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Ma Opcje</a><?php
			break;
		case 'time':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Godziny</a><?php
			break;
                case 'staff':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Personel</a><?php
			break;
                case 'site':
			?>&raquo; <a href="<?= $this->url(array('controller' => $this->controller, 'action' => 'list')); ?>">Strony</a><?php
			break;
	}

	// dodawanie sufix akcji
	switch ($this->action) {
		case 'add':	?>&raquo; Dodaj <?php break;
		case 'edit':?>&raquo; Edytuj<?php break;
		case 'move':?>&raquo; Przenieś<?php break;
	}
?>
</h2>

<ul class="options-list top-right small">
	<li><a title="Katalog" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'catalog',
  			'action'=>'list'
    	));
    ?>">Katalog</a></li>
    <li><a title="Obszary" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'district',
  			'action'=>'list'
    	));
    ?>">Obszary</a></li>
    <li><a title="Typ" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'type',
  			'action'=>'list'
    	));
    ?>">Typ</a></li>
    <li><a title="Usługi" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'service',
  			'action'=>'list'
    	));
    ?>">Usł.</a></li>
     <li><a title="Usługi" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'servicecost',
  			'action'=>'list'
    	));
    ?>"><abbr title="Koszty usług dla każdego wpisu">K.U.W.</abbr></a></li>
    <li><a title="Grafika" class="action small image" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'image',
  			'action'=>'list'
    	));
    ?>">Graf.</a></li>
    
    <li><a title="P.Typ" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'promotype',
  			'action'=>'list'
    	));
    ?>">P.Typ</a></li>
    <li><a title="P.Czas" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'promotime',
  			'action'=>'list'
    	));
    ?>">P.Czas</a></li>

    <li><a title="Opcje" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'options',
  			'action'=>'list'
    	));
    ?>">Opcje</a></li>
    <li><a title="M.Opcje" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'optionshas',
  			'action'=>'list'
    	));
    ?>">M.Opcje</a></li>
    
    <li><a title="Godziny" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'time',
  			'action'=>'list'
    	));
    ?>">Godziny</a></li>

    <li><a title="Personel" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'staff',
  			'action'=>'list'
    	));
    ?>">Personel</a></li>

    <li><a title="Strony" class="action small folder" href="<?php
    	print $this->url(array(
  			'module'=>'catalog',
  			'controller'=>'site',
  			'action'=>'list'
    	));
    ?>">Strony</a></li>
</ul>