<?php
	if ($this->catalogRow->meta_title != '') {
		$this->headTitle($this->catalogRow->meta_title);
	}
	$headMeta = $this->headMeta();
	if ($this->catalogRow->meta_keywords != '') {
		$headMeta->setName('keywords', $this->catalogRow->meta_keywords);
	}
	if ($this->catalogRow->meta_description != '') {
		$headMeta->appendName('description', $this->catalogRow->meta_description);
	}
?>

<div class="district span-18 last">
	<ul class="district-rowset">
		<?php if(count($this->districtRowset)):?>
		<?php foreach ($this->districtRowset as $row):?>
		<li><a href="<?php print $this->url(array('url' => $row->url),'catalogCategory')?>"><?php print $row->name?></a></li>
		<?php endforeach;?>
		<?php endif;?>
	</ul>
</div>

<div id="record-info">

<div class=" span-11">
	<h2><?php print $this->catalogRow->name ?></h2>
	
	<dl class="catalog-info">
		<dt>Adres</dt>
		<dd><?php print $this->catalogRow->adress ?></dd>

		<?php if(!empty($this->catalogRow->postcode)):?>
		<dt>Kod pocztowy</dt>
		<dd><?php print $this->catalogRow->postcode?></dd>
		<?php endif;?>
		
		<?php if (null !== $this->typeRow):?>
		<dt>Typ</dt>
		<dd>
			<span class="type-ico">
			<?php if(count($this->typeRow)):?>
				<img src="upload/catalog/ico/<?php print $this->typeRow->ico?>" title="<?php print $this->typeRow->name ?>" />
			<?php endif;?>
			</span>
			
			<span class="type-name">
			<?php print $this->typeRow->name ?>
			</span>			
		</dd>
		<?php endif;?>
	</dl>
</div>

<div class="images span-7 last">
	<?php if(!count($this->imagesRowset)):?>
	<p class="msg-notice">Fotografie nie zostały dodane!<br/>
		<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
			'module'=>'catalog',
			'controller'=>'index',
			'action'=>'update',
			'id' => $this->catalogRow->id
		),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
	<?php else: ?>
	<ul id="images-list">
	<?php
		//generowanie miniaturek
		foreach ($this->imagesRowset as $image):
	?>
		<li>
			<a href="<?php print $this->url(array('type' => "thumb3", 'file' => $image->image),'catalogImage');?>" rel="nofollow lightbox">
			<img src="<?php print $this->url(array('type' => "thumb1", 'file' => $image->image),'catalogImage');?>" /></a></li>
	<?php endforeach;?>
	</ul>
	<?php endif;?>
	
	<div class="clear"></div>
</div>

</div><!-- record-info -->

<div id="catalog-tabs"> 
<ul> 
	<li><a href="#service"><span>Usługi</span></a></li>
	<li><a href="#description"><span>Opis</span></a></li>
	<li class="more"><a href="#info-more"><span>Informacje <small>godziny otwarcia, formy płatności</small></span></a></li>
	<li class="ui-tabs-selected"><a href="#contact"><span>Kontakt</span></a></li>
</ul>

<div id="service">
<?php if(!count($this->serviceRowset)):?>
<p class="msg-notice">Informacje o świadczonych usługach nie zostały uzupełnione.
	<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
			'module'=>'catalog',
			'controller'=>'index',
			'action'=>'update',
			'id' => $this->catalogRow->id
		),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
<?php else: ?>
<dl>
<?php foreach ($this->serviceRowset as $sevice): ?>
	<dt>
		<span class="service-ico">
		<?php if(count($sevice->ico)):?>
			<img src="upload/catalog/ico_service/<?php print $sevice->ico?>" title="<?php print $sevice->name ?>" />
		<?php endif;?>
		</span>

		<span class="service-name"><?php print $sevice->name ?></span>
		od
		<span class="sercice-cost-min">
			<?php if($sevice->cost_min == '0.00'):?>
			cena minimalna nie została podana
			<?php else:?>
			<?php print $sevice->cost_min;?> <em>zł</em>
			<?php endif;?>
		</span>
		do
		<span class="sercice-cost-max">
			<?php if($sevice->cost_max == '0.00'):?>
			cena maksymalna nie została podana
			<?php else:?>
			<?php print $sevice->cost_max;?> <em>zł</em>
			<?php endif;?>
		</span>

		<span class="sercice-cost-max"></span>
	</dt>
	<dd><?php print $sevice->description?></dd>
<?php endforeach;?>
</dl>
<?php endif;?>
</div><!-- service -->

<div id="description"> 
	<?php if(empty($this->catalogRow->description)):?>
	<p class="msg-notice">Opis nie został uzupełniony.
		<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
			'module'=>'catalog',
			'controller'=>'index',
			'action'=>'update',
			'id' => $this->catalogRow->id
		),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
	<?php else:?>
	<?php print $this->catalogRow->description ?>
	<?php endif;?>
</div><!-- description -->

<div id="contact">
	<?php
		$www 	 = empty($this->catalogRow->www);
		$email 	 = empty($this->catalogRow->email);
		$contant = empty($this->catalogRow->contact);
	?>
	<?php if(!$www || !$email):?>
	<dl>
		<?php if(!$www):?>
		<dt>Strona WWW</dt><dd><?php print $this->catalogRow->www?></dd>
		<?php endif;?>
		<?php if(!$www):?>
		<dt>Adres e-mail</dt><dd><?php print $this->catalogRow->email?></dd>
		<?php endif;?>
	</dl>
	<?php endif;?>

	<?php if($contant && $www && $email):?>
	<p class="msg-notice">Kontakt nie został uzupełniony.
		<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
			'module'=>'catalog',
			'controller'=>'index',
			'action'=>'update',
			'id' => $this->catalogRow->id
		),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
	<?php else:?>
	<?php print $this->catalogRow->contact ?>
	<?php endif;?>
</div><!-- contact -->

<div id="info-more">
	<?php if(empty($this->catalogRow->info)):?>
	<p class="msg-notice">Informacje dodatkowe nie zostały uzupełnione.
		<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
			'module'=>'catalog',
			'controller'=>'index',
			'action'=>'update',
			'id' => $this->catalogRow->id
		),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
	<?php else:?>
	<?php print $this->catalogRow->info ?>
	<?php endif;?> 
</div><!-- info-more -->

</div><!-- catalog-tabs -->