<div class="span-17 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'imagedescription')) ?>
</div>
<div class="span-5 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj opis" class="action add" href="<?php
	    	print $this->url(array(
	  			'module'=>'gallery',
	  			'controller'=>'ImageDescription',
	  			'action'=>'add'
    		));
	    ?>">Dodaj opis</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
 <thead>
  <tr>
  	<th>Język</th>
    <th>Grafika</th>
    <th class="span-1">Edytuj</th>
    <th class="span-1">Usuń</th>
  </tr>
 </thead>
 <tbody>
  <?php if(count($this->rowset) < 1): ?>

   <tr>
    <td colspan="4"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'ImageDescription',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>"><?php print $row->language_url ?></a></td>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'ImageDescription',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>"><?php print $row->gallery_image_id ?></a></td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'gallery',
	  			'controller'=>'ImageDescription',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash ico small" href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'ImageDescription',
	  			'action'=>'delete',
	  			'id' => $row->id
    		));
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>