<div class="span-22 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'catalog','action' => 'add')) ?>
</div>

<hr class="bottom"/>
<?php print $this->form ?>

<!--<script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAnCqO9l1WMOgTCJlg9kVlMRT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSrIzx_bt1Rqqw5uvUzW0VTYiJ4dw"></script>-->
<!--<script type="text/javascript" src="js/jquery/jquery-1.2.6.pack.js"></script>-->
<!--<script type="text/javascript" src="js/jquery/ui/ui.core.js"></script>-->
<!--<script type="text/javascript" src="js/jquery/ui/ui.draggable.js"></script>-->
<!--<script type="text/javascript" src="js/jquery/ui/ui.dialog.js"></script>-->
<!--<script type="text/javascript" src="js/backend/catalog/complite_meta.js"></script>-->
<!--<script type="text/javascript" src="js/backend/catalog/gmaps.js"></script>-->

<?php
	$this->headScript()
		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAnCqO9l1WMOgTCJlg9kVlMRT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSrIzx_bt1Rqqw5uvUzW0VTYiJ4dw')
		->appendFile('js/jquery/jquery-1.2.6.pack.js')
		->appendFile('js/jquery/ui/ui.core.js')
		->appendFile('js/jquery/ui/ui.draggable.js')
		->appendFile('js/jquery/ui/ui.dialog.js')
		->appendFile('js/backend/catalog/complite_meta.js')
		->appendFile('js/backend/catalog/gmaps.js');
	
	$this->headLink()
		->appendStylesheet('js/jquery/themes/jquery-ui-themeroller/jquery-ui-themeroller.css');
?>