<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'calendar')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj wydarzenie" class="action add" href="<?php
	    	print $this->url(array(
	  			'controller'=>'calendar',
	  			'action'=>'add'
    		));
	    ?>">Dodaj wydarzenie</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
  <col span="1"/>
  <col class="odd"/>
  <col class="even" span="2"/>
 <thead>
  <tr>
    <th>Nazwa</th>
    <th class="span-3">Opis</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(empty($this->rowset)): ?>

   <tr>
    <td colspan="3"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'calendar',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>"><?php print $row->name ?></a></td>
    <td>
    	<a class="action list small" href="<?php
	    	print $this->url(
	    		array(
		  			'controller'=>'content',
		  			'action'=>'list',
		  			'calendar_id' => $row->id
	    		));
	    ?>">lista</a>
	    <a class="action add small" href="<?php
	    	print $this->url(
	    		array(
		  			'controller'=>'content',
		  			'action'=>'add',
		  			'calendar_id' => $row->id
	    		));
	    ?>">dodaj</a>
    </td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'calendar',
	  			'action'=>'edit',
	  			'id' => $row->id
    		));
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash small ico" href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'calendar',
	  			'action'=>'delete',
	  			'id' => $row->id
    		));
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>