<?php
	if (!$this->rowset):
?>
<p class="info-box">Nie znaleziono żanych klinik</p>
<?php
		return;
	endif;
?>

<select id="change-catalog">
	<option value="">Wybierz wizytówkę</option>
	<?php foreach($this->rowset as $row):?>
	<option value="<?php print $row->id;?>"><?php print $row->name;?></option>
	<?php endforeach;?>
</select>

<script type="text/javascript">
<!--
$('#change-catalog').change(function(){
	window.location.href = '<?php print $this->url(array(
		'module' => 'catalog',
		'controller' => 'management',
		'action' => 'edit',
		'id' => 'value'
	),'default',true);?>'.replace("value",this.value);
});
//-->
</script>