<div class="span-24 options-holder">
	<?= $this->partial('_partial/common_public_head.phtml', array('controller' => 'users')) ?>
</div>
<hr class="bottom" />

<div class="span-14">
	<?php print (string) $this->form->__toString();?>
</div>
<div class="span-10 last">
	<div class="msg-info">
		<p>W polu "Uczniowie" wypisz wszystkich uczniów należących do klasy.<br/>
		Dane ucznia należy wpisać w formacie: Nazwisko Imie.</p>
		<strong>Przykład:</strong>
		<p>
			Kowalski Jan<br/>
			Chrabąszcz Anna, Maria<br/>
		</p>
		<p>Każdorazowe wpisanie danych ucznia powinno rozpoczynać się od nowej linii!</p>
	</div>
</div>