<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'category','action' => 'edit')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj kategorię" class="action add" href="<?php
	    	print $this->url(array(
	  			'controller'=>'category',
	  			'action'=>'add'
    		));
	    ?>">Dodaj kategorię</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>