<div class="options-holder">
	<h2>Przypisz produkt do kategorii
		<sup>&raquo; <a href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Produkty</a></sup>
	</h2>
	<ul class="options-list top-right">
		<li><a title="Lista produktów" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Lista produktów</a></li>
	    <li><a title="Lista kategorii" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'category',
	  			'action'=>'list'
    		), 'default');
	    ?>">Lista kategorii</a></li>
	</ul>
</div>

<hr class="bottom"/>


<div class="span-18">
	<div class="lists folder">
	<?php
		$context .= $this->formSubmit('Przypisz','Przypisz');
		$context .= $this->treeCheckbox($this->rowset, $this->hasCategoriesArray);
		print $this->form('product-category', array(
			'method' => 'post',
			'action' => ''
		), $context);
	?>
	</div>
</div>
<div class="span-4 last">
	<?php
		if (null !== $this->product_id) {
			print $this->partial('_partial/product-create-menu.phtml',array(
				'where' => 'category',
				'product_id' =>$this->product_id
			));
		}
	?>
</div>