<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'comment')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj komentarz" class="action add" href="<?php
	    	print $this->url(array(
	    		'controller' => 'comment',
	  			'action'=>'add'
    		));
	    ?>">Dodaj komentarz</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
  <col span="2"/>
  <col class="even" span="3"/>
 <thead>
  <tr>
    <th>Aktualność</th>
    <th class="span-4">Data utworzenia</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(count($this->rowset) < 1): ?>

   <tr>
    <td colspan="5"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'comment',
	  			'action'=>'edit',
	  			'id' => $row->id
    		)
    	);
    ?>"><?php print $row->news_id ?></a></td>
    <td><?php print $row->t_create ?></td>
    <td class="center">
    	<?php
    		if ($row->moderate == 1) {
    			$moderateActionClass = 'true';
    			$publicatedValue = 0;
    		} else {
    			$moderateActionClass = 'false';
    			$moderateActionClass = 1;
    		}
    	?>
    	<a
    		title="Zmoderowane?"
    		class="action ico small <?= $moderateActionClass ?>"
    		href="<?php
		    	print $this->url(
		    		array(
		    			'controller' => 'comment',
			  			'action'=>'modify',
			  			'id' => $row->id,
		    			'm_moderate' => $moderateValue
		    		));
    	?>">moderacja</a>
    </td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'controller'=>'comment',
	  			'action'=>'edit',
	  			'id' => $row->id
    		)
    	);
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash ico small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'news',
	  			'controller'=>'comment',
	  			'action'=>'delete',
	  			'id' => $row->id
    		)
    	);
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>