<?php
	if ($this->catalogRow->meta_title != '') {
		$this->headTitle($this->catalogRow->meta_title);
	}
	$headMeta = $this->headMeta();
	if ($this->catalogRow->meta_keywords != '') {
		$headMeta->setName('keywords', $this->catalogRow->meta_keywords);
	}
	if ($this->catalogRow->meta_description != '') {
		$headMeta->appendName('description', $this->catalogRow->meta_description);
	}
?>

<div class="district span-18 last">
	<ul class="district-rowset">
		<?php if(count($this->districtRowset)):?>
		<?php foreach ($this->districtRowset as $row):?>
		<li><?php print $row->name?></li>
		<?php endforeach;?>
		<?php endif;?>
	</ul>
</div>

<div id="record-info">

<div class=" span-11">
	<h2><?php print $this->catalogRow->name ?></h2>
	
	<dl class="catalog-info">
		<dt>Adres</dt>
		<dd><?php print $this->catalogRow->adress ?></dd>
		<dt>Typ</dt>
		<dd>
			<span class="type-ico">
			<?php if(count($this->typeRow)):?>
				<img src="upload/catalog/ico/<?php print $this->typeRow->ico?>" title="<?php print $this->typeRow->name ?>" />
			<?php endif;?>
			</span>
			
			<span class="type-name">
			<?php print $this->typeRow->name ?>
			</span>
		</dd>
		<dt>Lat</dt><dd><?php print $this->catalogRow->lat ?></dd>
		<dt>Lng</dt><dd><?php print $this->catalogRow->lng ?></dd>
	</dl>
</div>

<div class="images span-7 last">
	<h3>Fotografie</h3>
	
	<?php if(!count($this->imagesRowset)):?>
	<p class="msg-notice">Brak fotografii osrodka!</p>
	<?php else: ?>
	<ul id="images-list">
	<?php
		//generowanie miniaturek
		foreach ($this->imagesRowset as $image):
	?>
		<li><img src="<?php print $this->url(array('type' => "thumb1", 'file' => $image->image),'catalogImage');?>" /></li>
	<?php endforeach;?>
	</ul>
	<?php endif;?>
	
	<div class="clear"></div>
</div>

</div><!-- record-info -->

<div id="catalog-tabs"> 
<ul> 
	<li><a href="#service"><span>Usługi</span></a></li> 
	<li><a href="#description"><span>Opis</span></a></li> 
	<li><a href="#info-more"><span>Dodatkowe informacje</span></a></li> 
</ul>

<div id="service">
<?php if(!count($this->serviceRowset)):?>
<p class="msg-notice">Brak informacji o świadczonych usługach</p>
<?php else: ?>
<dl>
<?php foreach ($this->serviceRowset as $sevice): ?>
	<dt>
		<span class="service-ico">
		<?php if(count($sevice->ico)):?>
			<img src="upload/catalog/ico_service/<?php print $sevice->ico?>" title="<?php print $sevice->name ?>" />
		<?php endif;?>
		</span>

		<span class="service-name"><?php print $sevice->name ?></span>
		od
		<span class="sercice-cost-min">
			<?php if($sevice->cost_min == '0.00'):?>
			cena minimalna nie została podana
			<?php else:?>
			<?php print $sevice->cost_min;?> <em>zł</em>
			<?php endif;?>
		</span>
		do
		<span class="sercice-cost-max">
			<?php if($sevice->cost_max == '0.00'):?>
			cena maksymalna nie została podana
			<?php else:?>
			<?php print $sevice->cost_max;?> <em>zł</em>
			<?php endif;?>
		</span>

		<span class="sercice-cost-max"></span>
	</dt>
	<dd><?php print $sevice->description?></dd>
<?php endforeach;?>
</dl>
<?php endif;?>
</div><!-- service -->

<div id="description"> 
	<p><b>Second tab is active</b></p><br> 
	<p>Alternative ways to specify the active tab will overrule this argument, listed in the order of their precedence:</p><br> 
	<ol> 
		<li>If a fragment identifier (hash) in the URL of the page refers to the id of a tab panel of a tab interface the corresponding tab will become the initial tab.</li> 
		<li>Same if you use the cookie option to save the latest selected tab in.</li> 
		<li>Last not least you can set the selected tab by attaching the selected tab class class (default: "ui-tabs-selected") to one of the <code>li</code> elements representing a single tab.</li> 
	</ol> 
</div><!-- description -->

<div id="info-more"> 
	Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 
	Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 
	Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 
</div><!-- info-more -->
</div><!-- catalog-tabs -->