<div id="overview">	
	<div class="span-12">
		<h2><?php print $this->catalogRow->name ?></h2>

		<div class="description">
			<?php print $this->partial('index/show/description.phtml', $this)?>
		</div>
	</div>

	<div class="span-3 half last">
		<div class="logo"
			<?php if (!empty($this->catalogRow->catalog_image_id)):?>
				<?php $catalogImageName = $this->logoFromRowset($this->catalogRow->catalog_image_id, $this->imagesRowset)?>
				style="background-image: url('<?php print $this->url(array('type' => "logo1", 'file' => $catalogImageName),'catalogImage');?>');"
			<?php endif;?>>
		</div>

		<div id="contact">
			<?php print $this->partial('index/show/contact.phtml', $this)?>
		</div>
	</div>
</div><!-- overview -->