<div class="span-22 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'admin')) ?>
</div>

<hr class="bottom"/>

<div class="span-14">
	<div class="span-5 border">
		<h3>Wybierz kategorię</h3>
		<select id="gallery-category" size="3"  style="width: 100%;"></select>
		<p class="bottom small">Galerie należące do kategorii</p>
		<select id="gallery-gallery" size="5" style="width: 100%;"></select>
	</div>
	<div class="span-9 last">
		<div class="options-holder">
			<h3>Zdięcia w galerii</h3>
			<ul class="options-list top-right">
				<li><a id="gallery-images-refresh" class="action refresh small" href="">odśwież</a></li>
			</ul>
		</div>
		<div id="gallery-images" class="gallery-images-list"></div>
	</div>
	
	<hr/>
	
	<div class="span-14 last">
		<div class="options-holder">
			<h3>Zdięcia nieprzypisane</h3>
			<ul class="options-list top-right">
				<li><a id="gallery-images-free-refresh" class="action refresh small" href="">odśwież</a></li>
			</ul>
		</div>
		<div id="gallery-images-free" class="gallery-images-list"></div>
	</div>
</div>
<div class="span-8 last">
	<form id="upload-form" enctype="multipart/form-data" method="post" action="<?php print $this->url(array('module' => 'gallery', 'controller' => 'image', 'action' => 'upload')) ?>">
	<?= $this->formFile('photoupload') ?>
	<?= $this->formSubmit(null, 'Uploaduj') ?>
	</form>
	
	<div class="clear"></div>
	<hr class="bottom"/>
	
	<form id="upload-form" action="<?php print KontorX_View_Helper_BaseUrl::getDomain() . $this->url(array('module' => 'gallery', 'controller' => 'image', 'action' => 'upload')) ?>">
		<p>
			<a class="action folder" href="#" id="demo-browse-images">Przeglądaj pliki</a> |
			<a class="action cancel" href="#" id="demo-clear">Wyczyść listę</a> |
			<a class="action attach" href="#" id="demo-upload">Upload</a>
		</p>
		<div class="msg-notice" id="upload-status">
			<span class="overall-title">Postęp w przesyłaniu plików:</span>
			<p class="progressbar-box bottom"><span class="progressbar-progress progress overall-progress"></span></p>
			<span class="current-title">Kopiowanie pliku:</span>
			<p class="progressbar-box bottom"><span class="progressbar-progress progress current-progress"></span></p>
	
			<div class="current-text"></div>
	
			<span class="arrow-lb"></span>
		</div>
		<ul id="upload-list"></ul>
	</form>
</div>