<div class="span-22 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'admin')) ?>
</div>

<hr class="bottom"/>

<div class="span-14">
	<div class="span-5 border">
		<h3>Wybierz kategorię</h3>
		<select id="gallery-category" size="3"  style="width: 100%;"></select>
		<p class="bottom small">Galerie należące do kategorii</p>
		<select id="gallery-gallery" size="5" style="width: 100%;"></select>
	</div>
	<div class="span-9 last">
		<div class="options-holder">
			<h3>Zdięcia w galerii</h3>
			<ul class="options-list top-right">
				<li><a id="gallery-images-refresh" class="action refresh small" href="">odśwież</a></li>
			</ul>
		</div>
		<div id="gallery-images" class="gallery-images-list"></div>
	</div>

	<hr/>

	<div class="span-14 last">
		<div class="options-holder">
			<h3>Zdięcia nieprzypisane</h3>
			<ul class="options-list top-right">
				<li><a id="gallery-images-free-refresh" class="action refresh small" href="">odśwież</a></li>
			</ul>
		</div>
		<div id="gallery-images-free" class="gallery-images-list"></div>
	</div>
</div>
<div class="span-8 last">

<?php
    $this->headScript()
      ->setAllowArbitraryAttributes(true)
      ->appendFile('js/dojo/dojo/dojo.js',null,array('djConfig'=>"isDebug:false, parseOnLoad: true, debugAtAllCosts:false"))
      ->appendFile('js/backend/gallery/dojo-gallery.js');
    $this->headLink()
      ->appendStylesheet('js/backend/gallery/dojo-gallery.css');
?>

    <h3 class="bottom">Załanczanie zdjęć</h3>
    <p class="msg-info small">Metoda podstawowa - działa na wyszystkich typach przeglądarek</p>
    <form id="upload-form" enctype="multipart/form-data" method="post" action="<?php print $this->url(array('module' => 'gallery', 'controller' => 'image', 'action' => 'upload')) ?>">
    <?= $this->formFile('photoupload') ?>
    <?= $this->formSubmit(null, 'Uploaduj') ?>
    </form>

    <p class="msg-info small">Metoda zaawansowana -umożliwia przesyłanie wielu plików jednocześnie. Nie działa na wszystkich typach przeglądarek!</p>
    <p id="hasFlash" class="small"><em>Flash Plugin mode</em></p>
    <p id="noFlash" class="small"><em>HTML file input overlay mode</em></p>

    <button id="btn0" class="browse" dojoType="dijit.form.Button">Przeglądaj zdjęcia</button>
    <button id="uploadBtn" class="uploadBtn" onClick="doUpload();" dojoType="dijit.form.Button">Uploaduj</button>
    <textarea cols="50" rows="6" id="fileToUpload"></textarea>

    <div id="rgtCol"></div>
</div>