<?php if (!count($this->rowsetImages)): ?>
<p class="msg-info">Zdięcia w galerii wkrótce</p>
<?php else: ?>
<div id="gallery" class="inline">
<dl>
	<?php foreach ($this->rowsetImages as $image): ?>
	<dt class="gallery-image <?= $image->image == $this->image ? 'selected' : '' ?>">
		<div class="image">
			<a rel="lightbox" href="<?php print $this->url(array('file' => $image->image,'type' => 'full'),'galleryImage')?>" title="<?php print $this->escape($image->name)?>">
				<img src="<?php print $this->url(array('file' => $image->image,'type' => 'thumb1'),'galleryImage') ?>" alt="<?php print $this->escape($image->name)?>" />
			</a>
		</div>
		<div class="name">
			<h4><a rel="lightbox" href="<?php print $this->url(array('file' => $image->image,'type' => 'full'),'galleryImage')?>" title="<?php print $this->escape($image->name)?>"><span>
				<?php print $this->escape($image->name)?></span></a></h4>
		</div>
	</dt>
	<dd class="description"><?php print $image->description?></dd>
	<?php endforeach; ?>
</dl>
</div>
<?php endif; ?>