<dl id="show-phone">
	<?php if (!empty($this->catalogRow->phone)):?>
	<dt>Pokaż numer telefonu</dt>
	<dd>
		<p class="phoneNr">Numer telefonu: <b><?php print $this->escape($this->catalogRow->phone)?></b></p>
		<p>Wspomnij o <a href="http://www.stomatolodzy.krakow.pl" title="Stomatolog, Kraków">stomatolodzy.krakow.pl</a> kiedy będziesz dzwonić</p>
	</dd>
	<?php else: ?>
	<dt>Telefon nie został podany!</dt>
	<?php endif;?>
</dl>
			
<dl id="addres">
	<dt>Adres</dt>
	<dd><?php print $this->catalogRow->adress ?></dd>

	<?php if(!empty($this->catalogRow->postcode)):?>
	<dt>Kod pocztowy</dt>
	<dd><?php print $this->catalogRow->postcode?></dd>
	<?php endif;?>
	
	<?php if (null !== $this->typeRow):?>
	<dt class="none">Typ</dt>
	<dd class="none">
		<span class="type-ico">
		<?php if(count($this->typeRow)):?>
			<img src="upload/catalog/type/<?php print $this->typeRow->ico?>" title="<?php print $this->typeRow->name ?>" />
		<?php endif;?>
		</span>
		
		<span class="type-name">
		<?php print $this->typeRow->name ?>
		</span>			
	</dd>
	<?php endif;?>

<?php
	$www 	 = empty($this->catalogRow->www);
	$email 	 = empty($this->catalogRow->email);
	$contant = empty($this->catalogRow->contact);
?>
<?php if(!$www || !$email):?>

	<?php if(!$www):?>
	<dt>Strona WWW</dt><dd><a href="<?php print $this->escape($this->catalogRow->www)?>"><?php print $this->catalogRow->www?></a></dd>
	<?php endif;?>

	<?php if(!$www):?>
	<dt>Adres e-mail</dt><dd><a href="mailto:<?php print $this->escape($this->catalogRow->email)?>"><?php print $this->catalogRow->email?></a></dd>
	<?php endif;?>

<?php endif;?>
</dl>
<!-- 
<?php //if($contant && $www && $email):?>
<p class="msg-notice">Kontakt nie został uzupełniony.
	<a class="vcard-update" rel="nofallow" href="<?php print $this->url(array(
		'module'=>'catalog',
		'controller'=>'index',
		'action'=>'update',
		'id' => $this->catalogRow->id
	),'default')?>">Dowiedz się jak uzupełnić wizytówkę.</a></p>
<?php //else:?>
<?php //print nl2br($this->catalogRow->contact) ?>
<?php //endif;?>
 -->