<div id="overview">	
	<div class="span-12">
		<div class="description">
			<?php print $this->partial('index/show/description.phtml', $this)?>
		</div>
	</div>

	<div class="span-3 half last">
		<div class="logo"
			<?php if (!empty($this->catalogRow->catalog_image_id)):?>
				<?php $catalogImageName = $this->logoFromRowset($this->catalogRow->catalog_image_id, $this->imagesRowset)?>
				style="background-image: url('<?php print $this->url(array('type' => "logo1", 'file' => $catalogImageName),'catalogImage');?>');"
			<?php endif;?>>
		</div>
	</div>
	
	<div class="span-5">
			<?php if (count($this->optionsRowset) > 0):?>
			<h3>Opcje</h3>
			<ul class="options small">
				<?php foreach ($this->optionsRowset as $option): ?>
				<li><?php print $option->name; ?></li>
				<?php endforeach;?>
			</ul>
			<?php endif;?>
		</div>
		<div class="span-5">
			<h3>Godziny otwarcia</h3>
			<?php if (count($this->optionsRowset) > 0):?>
			<ul class="options small">
				<?php foreach ($this->optionsRowset as $option): ?>
				<li><?php print $option->name; ?></li>
				<?php endforeach;?>
			</ul>
			<?php endif;?>
		</div>
		<div class="span-6 half last">
			<h3>Informacje kontaktowe</h3>
			<div id="contact" class="small">
				<?php print $this->partial('index/show/contact.phtml', $this)?>
			</div>
		</div>
</div><!-- overview -->