<?php if (!count($this->rowset)):?>
<p class="info-box">Nie znaleziono gabinetów</p>
<?php else:?>

<table>
	<col width="*%" />
	<col width="70" />
	<thead>
		<tr>
			<th colspan="2">Nazwa gabinetu</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->rowset as $row):?>
		<tr>
			<td>
				<a href="<?php print $this->url(array(
					'action'=>'edit',
					'id' => $row->id
				))?>"><?php print $row->name?></a>
			</td>
			<td>
				<a class="action edit" href="<?php print $this->url(array(
					'action'=>'edit',
					'id' => $row->id
				))?>">Edytuj</a>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>
<?php endif;?>