<div class="span-22 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'catalog','action' => 'add')) ?>
</div>

<hr class="bottom"/>
<?php print $this->form ?>

<?php
	$this->headScript()
		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key='.$this->apiKey)
		->appendFile('js/jquery/jquery-1.2.6.pack.js')
		->appendFile('js/jquery/ui/ui.core.js')
		->appendFile('js/jquery/ui/ui.draggable.js')
		->appendFile('js/jquery/ui/ui.dialog.js')
		->appendFile('js/backend/catalog/complite_meta.js')
		->appendFile('js/backend/catalog/gmaps.js');
	
	$this->headLink()
		->appendStylesheet('js/jquery/themes/jquery-ui-themeroller/jquery-ui-themeroller.css');
?>