<div class="span-18 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'catalog','action' => 'edit')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj wpis" class="action add" href="<?php
	    	print $this->url(array(
	  			'controller'=>'catalog',
	  			'action'=>'add'
    		));
	    ?>">Dodaj wpis</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>

<?php
	$this->headScript()
		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAnCqO9l1WMOgTCJlg9kVlMRScd4uuoniCqHZk8TRh2rI1gQbdrBSg5tTOx4YcGCXRk0Q_bCKoUGwr2Q')
//		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAnCqO9l1WMOgTCJlg9kVlMRREqxHjot-MVdGv4W7rNtdAWxNh4hS2-gRBnLrWFzhAC8SpBzYmGVYZgA')
//		->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAnCqO9l1WMOgTCJlg9kVlMRT2yXp_ZAY8_ufC3CFXhHIE1NvwkxSrIzx_bt1Rqqw5uvUzW0VTYiJ4dw')
		->appendFile('js/jquery/jquery-1.2.6.pack.js')
		->appendFile('js/jquery/ui/ui.core.js')
		->appendFile('js/jquery/ui/ui.draggable.js')
		->appendFile('js/jquery/ui/ui.dialog.js')
		->appendFile('js/backend/catalog/complite_meta.js')
		->appendFile('js/backend/catalog/gmaps.js');
	
	$this->headLink()
		->appendStylesheet('js/jquery/themes/jquery-ui-themeroller/jquery-ui-themeroller.css');
?>