<?php if (!count($this->rowsetImages)): ?>
<p class="msg-info">Zdięcia w galerii wkrótce</p>
<?php else: ?>
<div id="gallery" class="inline">
<dl>
	<?php foreach ($this->rowsetImages as $image): ?>
	<dt class="<?= $image->image == $this->image ? 'selected' : '' ?>">
		<div class="image">
			<a rel="lightbox" href="<?php print $this->url(array('file' => $image->image,'type' => 'full'),'galleryImage')?>" title="<?php print $this->escape($image->name)?>">
				<img src="<?php print $this->url(array('file' => $image->image,'type' => 'thumb1'),'galleryImage') ?>" alt="<?php print $this->escape($image->name)?>" />
				<div class="name"><span>
					<?php print $this->escape($image->name)?></span></div>
			</a>
		</div>
	</dt>
	<dd><div class="description"><?php print $image->description?></div></dd>
	<?php endforeach; ?>
</dl>
</div>
<?php endif; ?>