<?php
	$data = new KontorX_View_Helper_Date();
?>
<ul>
	<?php foreach ($this->rowset as $year => $months): ?>
	<li><a href="<?= $this->url(array('year' => $year),'newsArch',true) ?>"><?= $year ?></a>
		<ul>
			<?php foreach ($months as $month): ?>
			<li><a href="<?= $this->url(array('year' => $year, 'month' => $month),'newsArch') ?>"><?= $data->getMonthByNumber($month) ?></a></li>
			<?php endforeach; ?>
		</ul>
	</li>
	<?php endforeach; ?>
</ul>