<div class="span-18 last options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'user','action' => 'edit')) ?>
</div>
<div class="span-4 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj użytkownika" class="action add" href="<?php
	    	print $this->url(array(
	    		'controller' => 'user',
	  			'action'=>'add'
    		));
	    ?>">Dodaj użytkownika</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>