<?php
	$data = new KontorX_View_Helper_Date();
?>
<ul>
	<?php foreach ($this->rowset as $year => $months): ?>
	<li class="<?php print ($this->year == $year && $this->month == '') ? "selected" : ''?>"><a href="<?= $this->url(array('action' =>'index','year' => $year ,'month' => '')) ?>"><?= $year ?></a>
		<ul>
			<?php foreach ($months as $month): ?>
			<li class="<?php print ($this->year == $year && $this->month == $month) ? "selected" : ''?>">
				<a href="<?= $this->url(array('action' =>'index','year' => $year, 'month' => $month)) ?>"><?= $data->getMonthByNumber($month) ?></a></li>
			<?php endforeach; ?>
		</ul>
	</li>
	<?php endforeach; ?>
</ul>