<div class="options-holder">
	<h2>Dodaj grafikę
		<sup>&raquo; <a href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Produkty</a></sup>
	</h2>
	<ul class="options-list top-right">
		<li><a title="Lista produktów" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Lista produktów</a></li>
	    <li><a title="Lista grafik" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'image',
	  			'action'=>'list',
	    		'product_id' => $this->product_id
    		), 'default');
	    ?>">Lista grafik</a></li>
	</ul>
</div>

<hr class="bottom"/>
<div class="span-18">
	<?php print $this->form ?>
</div>
<div class="span-4 last">
	<?php
		if (null !== $this->product_id) {
			print $this->partial('_partial/product-create-menu.phtml',array(
				'where' => 'image',
				'product_id' =>$this->product_id
			));
		}
	?>
</div>