<div class="options-holder">
	<h2>Dodaj producenta
		<sup>&raquo; <a href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Produkty</a></sup>
	</h2>
	<ul class="options-list top-right">
		<li><a title="Lista produktów" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'admin',
	  			'action'=>'list'
    		), 'default');
	    ?>">Lista produktów</a></li>
	     <li><a title="Lista producentów" class="action list" href="<?php
	    	print $this->url(array(
	  			'module'=>'product',
	  			'controller'=>'manufacturer',
	  			'action'=>'list'
    		), 'default');
	    ?>">Lista producentów</a></li>
	</ul>
</div>

<hr class="bottom"/>
<?php print $this->form ?>