<div class="span-17 options-holder">
	<?= $this->partial('_partial/common_head.phtml', array('controller' => 'gallery')) ?>
</div>
<div class="span-5 last options-holder">
	<ul class="options-list top-right">
		<li><a title="Dodaj galerię" class="action add" href="<?php
	    	print $this->url(array(
	  			'module'=>'gallery',
	  			'controller'=>'gallery',
	  			'action'=>'add'
    		), 'default');
	    ?>">Dodaj galerię</a></li>
	</ul>
</div>

<hr class="bottom"/>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>

<hr class="bottom"/>

<table>
  <col span="2"/>
  <col class="odd" span="2"/>
  <col class="even" span="3"/>
 <thead>
  <tr>
    <th>Nazwa</th>
    <th class="span-5">Url</th>
    <th class="span-3">Zdięcia</th>
    <th class="span-3">Opis</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
    <th class="span-1">&nbsp;</th>
  </tr>
 </thead>
 <tbody>
  <?php if(count($this->rowset) < 1): ?>

   <tr>
    <td colspan="7"><p class="msg-notice bottom">Brak rekordów</p></td>
   </tr>

  <?php else: ?>

  <?php foreach ($this->rowset as $row): ?>
  <tr>
    <td><a href="<?php
    	print $this->url(
    		array(
	  			'module'=>'gallery',
	  			'controller'=>'gallery',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>"><?php print $row->name ?></a></td>
    <td class="small"><?php print $row->url ?></td>
    <td>
	    <a class="action list small" href="<?php
	    	print $this->url(
	    		array(
		  			'module'=>'gallery',
		  			'controller'=>'image',
		  			'action'=>'list',
		  			'gallery_id' => $row->id
	    		),'default'
	    	);
	    ?>">lista</a>
	    <a class="action add small" href="<?php
	    	print $this->url(
	    		array(
		  			'module'=>'gallery',
		  			'controller'=>'image',
		  			'action'=>'add',
		  			'gallery_id' => $row->id
	    		),'default'
	    	);
	    ?>">dodaj</a>
    </td>
    <td>
    	<a class="action list small" href="<?php
	    	print $this->url(
	    		array(
		  			'module'=>'gallery',
		  			'controller'=>'description',
		  			'action'=>'list',
		  			'gallery_id' => $row->id
	    		),'default'
	    	);
	    ?>">lista</a>
	    <a class="action add small" href="<?php
	    	print $this->url(
	    		array(
		  			'module'=>'gallery',
		  			'controller'=>'description',
		  			'action'=>'add',
		  			'gallery_id' => $row->id
	    		),'default'
	    	);
	    ?>">dodaj</a>
    </td>
    <td class="center">
    	<?php
    		if ($row->publicated == 1) {
    			$publicatedActionClass = 'true';
    			$publicatedValue = 0;
    		} else {
    			$publicatedActionClass = 'false';
    			$publicatedValue = 1;
    		}
    	?>
    	<a
    		title="Publikuj"
    		class="action ico small <?= $publicatedActionClass ?>"
    		href="<?php
		    	print $this->url(
		    		array(
			  			'module'=>'gallery',
			  			'controller'=>'gallery',
			  			'action'=>'modify',
			  			'id' => $row->id,
		    			'm_publicated' => $publicatedValue
		    		),'default'
		    	);
    ?>">publikacja</a></td>
    <td><a class="action edit small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'gallery',
	  			'controller'=>'gallery',
	  			'action'=>'edit',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">edytuj</a></td>
    <td class="center"><a
    	title="Usuń"
    	onclick="return confirm('Czy usunąć rekord?');"
    	class="action trash ico small" href="<?php
    	print $this->url(
    		array(
	  			'module'=>'gallery',
	  			'controller'=>'gallery',
	  			'action'=>'delete',
	  			'id' => $row->id
    		),'default'
    	);
    ?>">usuń</a></td>
  </tr>
  <?php endforeach; ?>

  <?php endif; ?>
 </tbody>
</table>

<div class="box text-right">
	<?= $pagination = $this->paginationControl($this->paginator, 'Sliding','_partial/pagination.phtml'); ?>
</div>
